<a href="https://colab.research.google.com/github/TejasKumarBoddu1/Data_Minning/blob/main/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[12,12,32],[44,15,63],[17,18,19]])
print("arr1+arr2")
print(arr1+arr2)
print("arr1-arr2")
print(arr1-arr2)
np.add(arr1,arr2)
np.subtract(arr1,arr2)

arr1+arr2
[[13 14 35]
 [48 20 69]
 [24 26 28]]
arr1-arr2
[[-11 -10 -29]
 [-40 -10 -57]
 [-10 -10 -10]]


array([[-11, -10, -29],
       [-40, -10, -57],
       [-10, -10, -10]])

In [21]:
import numpy as np

arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[7, 8, 9], [10, 11, 12]])
dot = np.dot(arr3, arr4)
ans = arr3 @ arr4
print("Matrix A")
print(arr3)
print("Matrix B")
print(arr4)
print("dot")
print(dot)
print("ans")
print(ans)


Matrix A
[[1 2]
 [3 4]
 [5 6]]
Matrix B
[[ 7  8  9]
 [10 11 12]]
dot
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]
ans
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]
